//
// Created by stalin on 16/12/2025.
//

#ifndef MODULO1_FUNDAMENTOS__04_FORMATACAO_H
#define MODULO1_FUNDAMENTOS__04_FORMATACAO_H

void Formatacao ();

#endif //MODULO1_FUNDAMENTOS__04_FORMATACAO_H