//
// Created by stalin on 17/12/2025.
//

#ifndef MODULO1_FUNDAMENTOS__08_PERCENTUALVOTOS_H
#define MODULO1_FUNDAMENTOS__08_PERCENTUALVOTOS_H

void PercentualVotos();

#endif //MODULO1_FUNDAMENTOS__08_PERCENTUALVOTOS_H