//
// Created by stalin on 17/12/2025.
//

#ifndef MODULO1_FUNDAMENTOS__09_REAJUSTESALARIAL_H
#define MODULO1_FUNDAMENTOS__09_REAJUSTESALARIAL_H

void reajusteSalarial9();

#endif //MODULO1_FUNDAMENTOS__09_REAJUSTESALARIAL_H