//
// Created by stalin on 17/12/2025.
//

#ifndef MODULO1_FUNDAMENTOS__11_PRECEDENCIAREFATORADO_H
#define MODULO1_FUNDAMENTOS__11_PRECEDENCIAREFATORADO_H

void precedencia();

#endif //MODULO1_FUNDAMENTOS__11_PRECEDENCIAREFATORADO_H