//
// Created by stalin on 17/12/2025.
//

#ifndef MODULO1_FUNDAMENTOS__12_INCREMENTOCOMPOSTO_H
#define MODULO1_FUNDAMENTOS__12_INCREMENTOCOMPOSTO_H

void incrementoComposto ();

#endif //MODULO1_FUNDAMENTOS__12_INCREMENTOCOMPOSTO_H